---
- name: Instalar Grafana y configurar repositorios
  hosts: all
  become: yes
  tasks:
    - name: Asegurarse de que el sistema esté actualizado
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalar paquetes necesarios
      apt:
        name:
          - software-properties-common
          - wget
        state: present

    - name: Agregar el repositorio de Grafana
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/release/deb stable main"
        state: present

    - name: Agregar la clave GPG para Grafana
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Agregar el repositorio de HashiCorp
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com jammy main"
        state: present

    - name: Agregar la clave GPG para HashiCorp
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Actualizar el caché de APT
      apt:
        update_cache: yes

    - name: Instalar Grafana
      apt:
        name: grafana
        state: present

    - name: Iniciar y habilitar Grafana
      systemd:
        name: grafana-server
        state: started
        enabled: yes