---
- name: instalar zabbix server
  hosts: zabbix_server
  become: yes
  tasks:
    - name: Instalar dependencias
      apt:
        name:
          - wget
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Agregar repositorio de Zabbix
      apt_repository:
        repo: "deb http://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu {{ ansible_lsb.codename }} main"
        state: present

    - name: ingresar clave repositorio de Zabbix
      apt_key:
        url: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/pool/main/z/zabbix/zabbix-release_{{ zabbix_version }}-1+ubuntu{{ ansible_lsb.codename }}_all.deb"
        state: present

    - name: instalar zabbix_server
      apt:
        name: "zabbix-server-mysql,zabbix-frontend,zabbix-apache-conf"
        state: present

    - name: instalar la base de datos
      apt:
        name: mariadb-server
        state: present

    - name: crear la DB
      mysql_db:
        name: zabbix
        state: present

    - name: crear el usuario admin
      mysql_user:
        name: zabbix
        password: "zabbixadmin"
        priv: "zabbix.*:ALL"
        state: present

    - name: importar esquema de base de datos
      command: "zcat /usr/share/doc/zabbix-server-mysql*/create/schema.sql.gz | mysql -uzabbix -pzabbix_password zabbix"

    - name: configurar server
      template:
        src: zabbix_server.conf.j2
        dest: /etc/zabbix/zabbix_server.conf

    - name: iniciar y habilitar servicios
      systemd:
        name: zabbix-server
        state: started
        enabled: yes