---
- name: instalar el agente de zabbix
  hosts: 192.168.0.27
  become: yes
  tasks:
    - name: instalar zabbix
      apt:
        name: zabbix-agent
        state: present

    - name: configurar el agente
      template:
        src: zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf

    - name: iniciar el agente
      systemd:
        name: zabbix-agent
        state: started
        enabled: yes