---
- name: Instalar Zabbix Server
  hosts: zabbix_server
  become: yes
  tasks:
    - name: Instalar dependencias
      apt:
        name:
          - software-properties-common
          - wget
        state: present

    - name: Agregar el repositorio de Zabbix
      apt_repository:
        repo: "deb http://repo.zabbix.com/zabbix/6.0/ubuntu focal main"
        state: present

    - name: Añadir la clave GPG del repositorio de Zabbix
      apt_key:
        url: "http://repo.zabbix.com/zabbix/6.0/ubuntu/focal/Release.key"
        state: present

    - name: Instalar Zabbix Server y Frontend
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-agent
          - mysql-server
        state: present

    - name: Configurar la base de datos MySQL para Zabbix
      mysql_db:
        name: zabbix
        state: present

    - name: Crear usuario de base de datos para Zabbix
      mysql_user:
        name: zabbix
        password: adminzabbix
        host: localhost
        priv: 'zabbix.*:ALL'
        state: present

    - name: Importar esquema y datos iniciales
      command: "mysql -uzabbix -pzabbix_password zabbix < /usr/share/doc/zabbix-server-mysql/create/schema.sql"
      args:
        warn: false

    - name: Iniciar y habilitar Zabbix Server
      systemd:
        name: zabbix-server
        state: started
        enabled: yes

    - name: Iniciar y habilitar Zabbix Agent
      systemd:
        name: zabbix-agent
        state: started
        enabled: yes