---
- name: instalar zabbix server
  hosts: zabbix_server
  become: yes
  tasks:
    - name: Instalar dependencias
      apt:
        name:
          - wget
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Agregar repositorio de Zabbix
      apt_repository:
        repo: "deb http://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu {{ ansible_lsb.codename }} main"
        state: present

    - name: Agregar clave del repositorio de Zabbix
      apt_key:
        url: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/pool/main/z/zabbix/zabbix-release_{{ zabbix_version }}-1+ubuntu{{ ansible_lsb.codename }}_all.deb"
        state: present

    - name: Instalar Zabbix Server
      apt:
        name: "zabbix-server-mysql,zabbix-frontend,zabbix-apache-conf"
        state: present

    - name: Instalar MariaDB
      apt:
        name: mariadb-server
        state: present

    - name: Crear base de datos para Zabbix
      mysql_db:
        name: zabbix
        state: present

    - name: Crear usuario de base de datos para Zabbix
      mysql_user:
        name: zabbix
        password: "zabbix_password"
        priv: "zabbix.*:ALL"
        state: present

    - name: Importar esquema de base de datos de Zabbix
      command: "zcat /usr/share/doc/zabbix-server-mysql*/create/schema.sql.gz | mysql -uzabbix -pzabbix_password zabbix"

    - name: Configurar Zabbix Server
      template:
        src: zabbix_server.conf.j2
        dest: /etc/zabbix/zabbix_server.conf

    - name: Iniciar y habilitar Zabbix Server
      systemd:
        name: zabbix-server
        state: started
        enabled: yes