---
- name: Instalar Zabbix Agent
  hosts: zabbix_agents
  become: yes
  tasks:
    - name: Instalar dependencias
      apt:
        name: zabbix-agent
        state: present

    - name: Configurar el archivo de configuración del agente
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: '192.168.0.47' 

    - name: Iniciar y habilitar Zabbix Agent
      systemd:
        name: zabbix-agent
        state: started
        enabled: yes